### ISSUE TITLE
Feedback op README

### ISSUE THREAD

**Issue by DivaniNL** [RenzoWille/look-and-feel-styleguide#8]
Ik kan hier geen feedback op geven. De Readme mist.
Feedback gegeven door: @karima002 @fatimahilali @mikiyas-hs @naddybs @raffa

**Comment by RenzoWille** [comment]
@senneb31  opgelost: https://github.com/RenzoWille/look-and-feel-styleguide/commit/ef21ba8eca8ca9a68c05fcb19b185f6e4c226f7a
